/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Giacomo Salvador
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBaseAdmin = new javax.swing.JPanel();
        panFotoPerfil = new javax.swing.JPanel();
        lblAdminFoto = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        panDescripcion = new javax.swing.JPanel();
        txtAdminPaterno = new javax.swing.JLabel();
        txtAdminMaterno = new javax.swing.JLabel();
        txtAdminCargo = new javax.swing.JLabel();
        txtAdminDNI = new javax.swing.JLabel();
        txtAdminCorreo = new javax.swing.JLabel();
        txtAdminCelular = new javax.swing.JLabel();
        lblAdminPaterno = new javax.swing.JLabel();
        lblAdminMaterno = new javax.swing.JLabel();
        lblAdminCargo = new javax.swing.JLabel();
        lblAdminDNI = new javax.swing.JLabel();
        lblAdminCorreo = new javax.swing.JLabel();
        lblAdminCelular = new javax.swing.JLabel();
        txtAdminRed = new javax.swing.JLabel();
        btnRegistroContratos = new javax.swing.JToggleButton();
        btnRegistroUsuarios = new javax.swing.JToggleButton();
        btnRegistroHorarios = new javax.swing.JToggleButton();
        btnAdminActualizarInfo = new javax.swing.JToggleButton();
        btnLogOut = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JEMS | Administrador");
        setMinimumSize(new java.awt.Dimension(500, 550));
        setSize(new java.awt.Dimension(500, 550));

        panBaseAdmin.setBackground(new java.awt.Color(255, 255, 255));
        panBaseAdmin.setMinimumSize(new java.awt.Dimension(500, 550));
        panBaseAdmin.setPreferredSize(new java.awt.Dimension(500, 550));

        panFotoPerfil.setBackground(new java.awt.Color(255, 255, 255));

        lblAdminFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N

        javax.swing.GroupLayout panFotoPerfilLayout = new javax.swing.GroupLayout(panFotoPerfil);
        panFotoPerfil.setLayout(panFotoPerfilLayout);
        panFotoPerfilLayout.setHorizontalGroup(
            panFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAdminFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panFotoPerfilLayout.setVerticalGroup(
            panFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAdminFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );

        lblAdminName.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        lblAdminName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminName.setText("name");

        panDescripcion.setBackground(new java.awt.Color(255, 255, 255));

        txtAdminPaterno.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        txtAdminPaterno.setText("Apellido Paterno:");

        txtAdminMaterno.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        txtAdminMaterno.setText("Apellido Materno:");

        txtAdminCargo.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        txtAdminCargo.setText("Cargo:");

        txtAdminDNI.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        txtAdminDNI.setText("DNI:");

        txtAdminCorreo.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        txtAdminCorreo.setText("Correo Electrónico:");

        txtAdminCelular.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        txtAdminCelular.setText("Celular:");

        lblAdminPaterno.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        lblAdminPaterno.setText("surnameF");

        lblAdminMaterno.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        lblAdminMaterno.setText("surnameM");

        lblAdminCargo.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        lblAdminCargo.setText("position");

        lblAdminDNI.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        lblAdminDNI.setText("dni");

        lblAdminCorreo.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        lblAdminCorreo.setText("user");

        lblAdminCelular.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        lblAdminCelular.setText("phone");

        javax.swing.GroupLayout panDescripcionLayout = new javax.swing.GroupLayout(panDescripcion);
        panDescripcion.setLayout(panDescripcionLayout);
        panDescripcionLayout.setHorizontalGroup(
            panDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAdminCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdminDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdminCargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdminMaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdminPaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdminCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAdminCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAdminDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAdminCargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAdminMaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAdminCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminPaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDescripcionLayout.setVerticalGroup(
            panDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDescripcionLayout.createSequentialGroup()
                        .addComponent(lblAdminPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdminMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdminCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblAdminDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdminCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAdminCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDescripcionLayout.createSequentialGroup()
                        .addComponent(txtAdminPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdminMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtAdminCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtAdminDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdminCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAdminCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        txtAdminRed.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        txtAdminRed.setForeground(new java.awt.Color(255, 0, 0));
        txtAdminRed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdminRed.setText("ADMIN");

        btnRegistroContratos.setBackground(new java.awt.Color(0, 48, 80));
        btnRegistroContratos.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        btnRegistroContratos.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroContratos.setText("Modulo de Contratos");
        btnRegistroContratos.setToolTipText("");
        btnRegistroContratos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistroContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroContratosActionPerformed(evt);
            }
        });

        btnRegistroUsuarios.setBackground(new java.awt.Color(0, 48, 80));
        btnRegistroUsuarios.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        btnRegistroUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroUsuarios.setText("Modulo de Usuarios");
        btnRegistroUsuarios.setToolTipText("");
        btnRegistroUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistroUsuarios.setPreferredSize(new java.awt.Dimension(185, 26));
        btnRegistroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUsuariosActionPerformed(evt);
            }
        });

        btnRegistroHorarios.setBackground(new java.awt.Color(0, 48, 80));
        btnRegistroHorarios.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        btnRegistroHorarios.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroHorarios.setText("Modulo de Horarios");
        btnRegistroHorarios.setToolTipText("");
        btnRegistroHorarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistroHorarios.setPreferredSize(new java.awt.Dimension(185, 26));
        btnRegistroHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroHorariosActionPerformed(evt);
            }
        });

        btnAdminActualizarInfo.setBackground(new java.awt.Color(0, 48, 80));
        btnAdminActualizarInfo.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        btnAdminActualizarInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminActualizarInfo.setText("Actualizar Información");
        btnAdminActualizarInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdminActualizarInfo.setPreferredSize(new java.awt.Dimension(185, 26));

        btnLogOut.setFont(new java.awt.Font("Lexend", 0, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(0, 48, 80));
        btnLogOut.setText("Cerrar Sesión");
        btnLogOut.setAutoscrolls(true);
        btnLogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBaseAdminLayout = new javax.swing.GroupLayout(panBaseAdmin);
        panBaseAdmin.setLayout(panBaseAdminLayout);
        panBaseAdminLayout.setHorizontalGroup(
            panBaseAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBaseAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBaseAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panBaseAdminLayout.createSequentialGroup()
                        .addGroup(panBaseAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdminRed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panBaseAdminLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(panFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(panBaseAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panBaseAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panBaseAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistroContratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistroHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistroUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdminActualizarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)))
                .addGap(22, 22, 22))
        );
        panBaseAdminLayout.setVerticalGroup(
            panBaseAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBaseAdminLayout.createSequentialGroup()
                .addGroup(panBaseAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBaseAdminLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtAdminRed, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panFotoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(panBaseAdminLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnLogOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnRegistroContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRegistroUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnRegistroHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAdminActualizarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBaseAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBaseAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroContratosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroContratosActionPerformed

    private void btnRegistroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroUsuariosActionPerformed

    private void btnRegistroHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroHorariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroHorariosActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton btnAdminActualizarInfo;
    public javax.swing.JToggleButton btnLogOut;
    public javax.swing.JToggleButton btnRegistroContratos;
    public javax.swing.JToggleButton btnRegistroHorarios;
    public javax.swing.JToggleButton btnRegistroUsuarios;
    public javax.swing.JLabel lblAdminCargo;
    public javax.swing.JLabel lblAdminCelular;
    public javax.swing.JLabel lblAdminCorreo;
    public javax.swing.JLabel lblAdminDNI;
    private javax.swing.JLabel lblAdminFoto;
    public javax.swing.JLabel lblAdminMaterno;
    private javax.swing.JLabel lblAdminName;
    public javax.swing.JLabel lblAdminPaterno;
    private javax.swing.JPanel panBaseAdmin;
    private javax.swing.JPanel panDescripcion;
    private javax.swing.JPanel panFotoPerfil;
    private javax.swing.JLabel txtAdminCargo;
    private javax.swing.JLabel txtAdminCelular;
    private javax.swing.JLabel txtAdminCorreo;
    private javax.swing.JLabel txtAdminDNI;
    private javax.swing.JLabel txtAdminMaterno;
    private javax.swing.JLabel txtAdminPaterno;
    private javax.swing.JLabel txtAdminRed;
    // End of variables declaration//GEN-END:variables
}
